# Generated by Django 4.0.6 on 2022-07-12 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=127)),
                ('password', models.CharField(max_length=127)),
                ('especialidade', models.CharField(max_length=127)),
                ('telefone', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]