# Generated by Django 4.0.6 on 2022-07-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agenda_medico_id'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='agenda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda'),
        ),
    ]
