# Generated by Django 4.0.6 on 2022-07-13 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agenda_medico_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='password',
        ),
        migrations.AddField(
            model_name='medico',
            name='agenda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agendas.agenda'),
        ),
        migrations.AddField(
            model_name='medico',
            name='registro_profissional',
            field=models.CharField(default=None, max_length=127, unique=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
