# Generated by Django 4.0.6 on 2022-07-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_medico_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
    ]
