# Generated by Django 4.0.6 on 2022-07-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_remove_medico_email_remove_medico_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='agenda',
        ),
    ]
