# Generated by Django 4.0.6 on 2022-07-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_medico_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='agente_de_saude',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='dias_de_atendimento',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='medico',
            name='registro_profissional',
            field=models.CharField(default=None, max_length=127),
        ),
    ]
