# Generated by Django 4.0.6 on 2022-07-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_agente_de_saude_medico_dias_de_atendimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='password',
            new_name='senha',
        ),
    ]
