# Generated by Django 4.0.6 on 2022-07-18 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0004_medico_email_medico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL),
        ),
    ]
