# Generated by Django 4.0.6 on 2022-07-14 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_ativo_paciente_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
