# Generated by Django 4.0.6 on 2022-07-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_convenio_tipo'),
        ('pacientes', '0003_paciente_atualizado_em_paciente_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='convenios.convenio'),
        ),
    ]
