# Generated by Django 4.0.6 on 2022-07-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_convenio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='criado_em',
        ),
    ]
