# Generated by Django 4.0.6 on 2022-08-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
