# Generated by Django 4.0.6 on 2022-08-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0002_alter_convenio_tipo'),
        ('pacientes', '0007_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='convenios.convenio'),
        ),
    ]
