# Generated by Django 4.0.6 on 2022-07-12 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 12, 13, 54, 1, 124770))),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='pacientes.paciente')),
            ],
        ),
    ]
