

# Generated by Django 4.0.6 on 2022-07-12 20:42



import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='criado_em',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 12, 16, 42, 36, 449903)),

        ),
    ]
