# Generated by Django 4.0.6 on 2022-07-13 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0010_alter_anamnese_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='criado_em',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 11, 7, 53, 333960)),
        ),
    ]
