# Generated by Django 4.0.6 on 2022-07-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0014_alter_anamnese_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
