# Generated by Django 4.0.6 on 2022-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agente_de_saude',
            field=models.BooleanField(default=False),
        ),
    ]
