# Generated by Django 4.0.6 on 2022-07-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_atualizado_em_usuario_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
