# Generated by Django 4.0.6 on 2022-09-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
