# Generated by Django 4.0.6 on 2022-07-12 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('compareceu', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('convenio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='convenios.convenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='medicos.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='pacientes.paciente')),
            ],
        ),
    ]
