# Generated by Django 4.0.6 on 2022-07-12 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_da_consulta',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
