# Generated by Django 4.0.6 on 2022-07-14 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_consulta_data_da_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='convenio',
        ),
        migrations.AddField(
            model_name='consulta',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='criado_em',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
