# Generated by Django 4.0.6 on 2022-07-14 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_remove_consulta_convenio_consulta_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
