# Generated by Django 4.0.6 on 2022-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_remove_consulta_data_da_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_da_consulta',
            field=models.DateField(blank=True, default=None),
        ),
    ]
