# Generated by Django 4.0.6 on 2022-07-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0006_remove_agenda_data_consulta_and_more'),
        ('consultas', '0014_alter_consulta_data_da_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='data_da_consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='horário_agenda',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consulta', to='agendas.agenda'),
        ),
    ]
