# Generated by Django 4.0.6 on 2022-07-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_agenda_consulta'),
        ('consultas', '0016_rename_horário_agenda_consulta_horario_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario_agenda',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Consulta', to='agendas.agenda'),
        ),
    ]
