# Generated by Django 4.0.6 on 2022-07-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0017_alter_consulta_horario_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='horario_agenda',
        ),
    ]
