# Generated by Django 4.0.6 on 2022-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0018_remove_consulta_horario_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
