# Generated by Django 4.0.6 on 2022-07-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0019_consulta_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='horario',
            field=models.DateTimeField(null=True),
        ),
    ]
