# Generated by Django 4.0.6 on 2022-09-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0020_consulta_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='consulta_cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
