# Generated by Django 4.0.6 on 2022-07-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_remove_medico_agenda'),
        ('consultas', '0005_alter_consulta_criado_em'),
        ('agendas', '0002_agenda_medico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='medico_id',
        ),
        migrations.AddField(
            model_name='agenda',
            name='consulta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='consultas.consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.medico'),
        ),
    ]
