# Generated by Django 4.0.6 on 2022-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_remove_agenda_medico_id_agenda_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_consulta',
            field=models.CharField(max_length=100),
        ),
    ]
