# Generated by Django 4.0.6 on 2022-07-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_alter_medico_usuario'),
        ('consultas', '0014_alter_consulta_data_da_consulta'),
        ('agendas', '0004_alter_agenda_data_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='consultas.consulta'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.medico'),
        ),
    ]
