# Generated by Django 4.0.6 on 2022-07-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0014_alter_consulta_data_da_consulta'),
        ('agendas', '0005_alter_agenda_consulta_alter_agenda_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='data_consulta',
        ),
        migrations.AddField(
            model_name='agenda',
            name='descricao_da_consulta',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='dia_da_consulta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario_inicial',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='consulta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='consultas.consulta'),
        ),
    ]
