# Generated by Django 4.0.6 on 2022-07-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0016_rename_horário_agenda_consulta_horario_agenda'),
        ('agendas', '0006_remove_agenda_data_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='consulta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='consultas.consulta'),
        ),
    ]
