# Generated by Django 4.0.6 on 2022-07-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0007_alter_agenda_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='consulta',
        ),
    ]
