# Generated by Django 4.0.6 on 2022-07-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0018_remove_consulta_horario_agenda'),
        ('agendas', '0008_remove_agenda_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='consultas.consulta'),
        ),
    ]
