# Generated by Django 4.0.6 on 2022-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0009_agenda_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='data_hora_inicial',
            field=models.DateTimeField(null=True),
        ),
    ]
