# Generated by Django 4.0.6 on 2022-07-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0010_agenda_data_hora_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='descricao_da_consulta',
        ),
    ]
